// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHLtsY2G9OL3m-KFS4nb4aVf50rZzXuFQ',
    appId: '1:562673538895:web:6d2c02feb2dbf668ce973a',
    messagingSenderId: '562673538895',
    projectId: 'gsc2023-food-app',
    authDomain: 'gsc2023-food-app.firebaseapp.com',
    storageBucket: 'gsc2023-food-app.appspot.com',
    measurementId: 'G-5NBVS047Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlBLDNjE0DC9wU3yN0ddde6mScctG0kpI',
    appId: '1:562673538895:android:e1635f03c947cb85ce973a',
    messagingSenderId: '562673538895',
    projectId: 'gsc2023-food-app',
    storageBucket: 'gsc2023-food-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbe2w2zVskb8Ti7Df4_oD5UqU9mld92K4',
    appId: '1:562673538895:ios:bcf135bffbe16a9ece973a',
    messagingSenderId: '562673538895',
    projectId: 'gsc2023-food-app',
    storageBucket: 'gsc2023-food-app.appspot.com',
    iosClientId: '562673538895-tltfou581o444nlrc8h5puurp1o9h1sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gsc2023FoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbe2w2zVskb8Ti7Df4_oD5UqU9mld92K4',
    appId: '1:562673538895:ios:bcf135bffbe16a9ece973a',
    messagingSenderId: '562673538895',
    projectId: 'gsc2023-food-app',
    storageBucket: 'gsc2023-food-app.appspot.com',
    iosClientId: '562673538895-tltfou581o444nlrc8h5puurp1o9h1sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gsc2023FoodApp',
  );
}
